<?php
\App\Models\Product::create(['name' => 'Sofá Retrátil 3 lugares Reclinável', 'description' => 'Suede cinza 2.50m', 'quantity' => 4, 'cost_price' => 2200.00, 'sale_price' => 3890.00]);
\App\Models\Product::create(['name' => 'Colchão Queen Ortobom Light Molas', 'description' => 'Espuma D33 158x198x24cm', 'quantity' => 8, 'cost_price' => 1200.00, 'sale_price' => 2199.00]);
\App\Models\Product::create(['name' => 'Guarda-roupa Casal 6 portas 8 gavetas', 'description' => 'Madeira MDF branco', 'quantity' => 6, 'cost_price' => 980.00, 'sale_price' => 1699.00]);
\App\Models\Product::create(['name' => 'Mesa de Jantar 8 cadeiras Madeira Maciça', 'description' => 'Tampo 2.00m imbuia', 'quantity' => 3, 'cost_price' => 2800.00, 'sale_price' => 4990.00]);
\App\Models\Product::create(['name' => 'Cooktop 5 bocas a gás Fischer', 'description' => 'Vidro temperado preto', 'quantity' => 12, 'cost_price' => 680.00, 'sale_price' => 1149.00]);
\App\Models\Product::create(['name' => 'Forno Elétrico de Embutir 80L Mueller', 'description' => 'Espelhado com grill', 'quantity' => 7, 'cost_price' => 1400.00, 'sale_price' => 2299.00]);
\App\Models\Product::create(['name' => 'Adega Climatizada 34 garrafas Philco', 'description' => 'Dual zone touch', 'quantity' => 5, 'cost_price' => 2200.00, 'sale_price' => 3499.00]);
\App\Models\Product::create(['name' => 'Cervejeira Consul 82L Titanium', 'description' => 'Frost free 5 prateleiras', 'quantity' => 4, 'cost_price' => 1800.00, 'sale_price' => 2799.00]);
\App\Models\Product::create(['name' => 'Máquina de Lavar 14kg Brastemp', 'description' => 'Abertura superior branca', 'quantity' => 6, 'cost_price' => 1600.00, 'sale_price' => 2499.00]);
\App\Models\Product::create(['name' => 'Secadora de Roupas Mueller 12kg', 'description' => 'Parede ou chão', 'quantity' => 5, 'cost_price' => 1400.00, 'sale_price' => 2199.00]);
\App\Models\Product::create(['name' => 'Pipoqueira Elétrica Cadence Pop Mais', 'description' => '220V vermelha', 'quantity' => 60, 'cost_price' => 85.00, 'sale_price' => 159.90]);
\App\Models\Product::create(['name' => 'Grill Elétrico Mondial 1800W', 'description' => 'Antiaderente abre 180°', 'quantity' => 25, 'cost_price' => 180.00, 'sale_price' => 329.90]);
\App\Models\Product::create(['name' => 'Sanduicheira Minigrill Britânia', 'description' => 'Placas antiaderentes', 'quantity' => 40, 'cost_price' => 95.00, 'sale_price' => 179.90]);
\App\Models\Product::create(['name' => 'Mixer 3 em 1 Mondial Turbo 600W', 'description' => 'Copo + batedor de claras', 'quantity' => 35, 'cost_price' => 140.00, 'sale_price' => 259.90]);
\App\Models\Product::create(['name' => 'Torradeira Oster Chrome 800W', 'description' => '7 níveis de tostagem', 'quantity' => 20, 'cost_price' => 180.00, 'sale_price' => 329.90]);
\App\Models\Product::create(['name' => 'Escada Alumínio 6 degraus Mor', 'description' => 'Suporta 120kg', 'quantity' => 15, 'cost_price' => 220.00, 'sale_price' => 399.00]);
\App\Models\Product::create(['name' => 'Furadeira de Impacto Bosch 650W', 'description' => '13mm + maleta', 'quantity' => 18, 'cost_price'=> 222.00, 'sale_price' => 429.00]);
\App\Models\Product::create(['name' => 'Jogo de Chaves Combinadas Tramontina 12pçs', 'description' => '8 a 22mm cromo vanádio', 'quantity' => 30, 'cost_price' => 180.00, 'sale_price' => 349.90]);
\App\Models\Product::create(['name' => 'Kit Ferramentas 129 peças Sparta', 'description' => 'Maleta completa', 'quantity' => 10, 'cost_price' => 280.00, 'sale_price' => 499.90]);
\App\Models\Product::create(['name' => 'Pneu Aro 17 Michelin Primacy 4 225/45', 'description' => 'Cada pneu', 'quantity' => 20, 'cost_price' => 680.00, 'sale_price' => 949.00]);
\App\Models\Product::create(['name' => 'Óleo Motor 5W30 Sintético Mobil 1', 'description' => 'Galão 4 litros', 'quantity' => 40, 'cost_price' => 180.00, 'sale_price' => 299.90]);
\App\Models\Product::create(['name' => 'Bateria Moura 60Ah Selada', 'description' => 'Carro popular', 'quantity' => 12, 'cost_price' => 380.00, 'sale_price' => 599.00]);
\App\Models\Product::create(['name' => 'Tapete Higiênico Pet 30un Super Secão', 'description' => '80x60cm', 'quantity' => 50, 'cost_price' => 65.00, 'sale_price' => 119.90]);
\App\Models\Product::create(['name' => 'Ração Golden Gatos Adultos 10,1kg', 'description' => 'Salmão', 'quantity' => 15, 'cost_price' => 220.00, 'sale_price' => 369.90]);
\App\Models\Product::create(['name' => 'Cama Pet Impermeável Tamanho G', 'description' => 'Cinza com plush', 'quantity' => 20, 'cost_price' => 140.00, 'sale_price' => 279.90]);
\App\Models\Product::create(['name' => 'Bebedouro Automático 2L Truqys', 'description' => 'Fonte elétrica para gatos', 'quantity' => 25, 'cost_price' => 120.00, 'sale_price' => 229.90]);
\App\Models\Product::create(['name' => 'Brinquedo Mordedor KONG Extreme M', 'description' => 'Borracha resistente', 'quantity' => 40, 'cost_price' => 85.00, 'sale_price' => 159.90]);
\App\Models\Product::create(['name' => 'Shampoo Antipulgas Pet Society 5L', 'description' => 'Concentrado', 'quantity' => 10, 'cost_price' => 180.00, 'sale_price' => 329.90]);
\App\Models\Product::create(['name' => 'Cadeira de Rodas Dobrável Alumínio', 'description' => 'Até 120kg', 'quantity' => 3, 'cost_price' => 980.00, 'sale_price' => 1699.00]);
\App\Models\Product::create(['name' => 'Nebulizador/Inalador Omron', 'description' => 'Uso adulto e infantil', 'quantity' => 12, 'cost_price' => 180.00, 'sale_price' => 329.90]);
\App\Models\Product::create(['name' => 'Medidor de Pressão Digital G-Tech', 'description' => 'Braço automático', 'quantity' => 30, 'cost_price' => 95.00, 'sale_price' => 179.90]);
\App\Models\Product::create(['name' => 'Termômetro Infravermelho Sem Contato', 'description' => 'Testa 1 segundo', 'quantity' => 50, 'cost_price' => 120.00, 'sale_price' => 229.90]);
\App\Models\Product::create(['name' => 'Oxímetro de Pulso G-Tech', 'description' => 'Display OLED', 'quantity' => 40, 'cost_price' => 85.00, 'sale_price' => 159.90]);
\App\Models\Product::create(['name' => 'Suporte TV Articulado 32 a 70"', 'description' => 'Inclinação e giro', 'quantity' => 20, 'cost_price' => 180.00, 'sale_price' => 329.90]);
\App\Models\Product::create(['name' => 'Antena Digital Interna Aquário', 'description' => 'Alcance 50km', 'quantity' => 35, 'cost_price' => 95.00, 'sale_price' => 179.90]);
\App\Models\Product::create(['name' => 'Conversor Digital + Gravador Intelbras', 'description' => 'Full HD', 'quantity' => 25, 'cost_price' => 180.00, 'sale_price' => 299.90]);
\App\Models\Product::create(['name' => 'Roteador TP-Link Archer AX55 Wi-Fi 6', 'description' => 'Dual Band 3000Mbps', 'quantity' => 18, 'cost_price' => 420.00, 'sale_price' => 749.00]);
\App\Models\Product::create(['name' => 'Nobreak SMS 1500VA Bivolt', 'description' => '8 tomadas', 'quantity' => 8, 'cost_price' => 980.00, 'sale_price' => 1499.00]);
\App\Models\Product::create(['name' => 'Webcam Logitech C920s Pro Full HD', 'description' => 'Com tampa privacidade', 'quantity' => 20, 'cost_price' => 380.00, 'sale_price' => 649.00]);
\App\Models\Product::create(['name' => 'Headset Gamer Redragon Zeus X', 'description' => '7.1 RGB USB', 'quantity' => 30, 'cost_price' => 280.00, 'sale_price' => 499.90]);
\App\Models\Product::create(['name' => 'Pen Drive 128GB Kingston', 'description' => 'USB 3.2 metal', 'quantity' => 60, 'cost_price' => 85.00, 'sale_price' => 159.90]);
\App\Models\Product::create(['name' => 'Cartão Micro SD 256GB Sandisk Ultra', 'description' => '100MB/s com adaptador', 'quantity' => 50, 'cost_price' => 120.00, 'sale_price' => 229.90]);
\App\Models\Product::create(['name' => 'Carregador Turbo 65W Anker 3 portas', 'description' => 'GaN USB-C + USB-A', 'quantity' => 40, 'cost_price' => 180.00, 'sale_price' => 329.90]);
\App\Models\Product::create(['name' => 'Cabo HDMI 2.1 8K 3 metros', 'description' => 'Certificado ultra high speed', 'quantity' => 50, 'cost_price' => 65.00, 'sale_price' => 129.90]);
\App\Models\Product::create(['name' => 'Luminária de Mesa LED Touch', 'description' => '3 temperaturas de cor USB', 'quantity' => 45, 'cost_price' => 85.00, 'sale_price' => 159.90]);
\App\Models\Product::create(['name' => 'Fita LED 5m RGB 5050', 'description' => 'Controle remoto + fonte', 'quantity' => 35, 'cost_price' => 95.00, 'sale_price' => 179.90]);
\App\Models\Product::create(['name' => 'Interruptor Inteligente Wi-Fi Sonoff', 'description' => 'Controle por app', 'quantity' => 60, 'cost_price' => 65.00, 'sale_price' => 129.90]);
\App\Models\Product::create(['name' => 'Tomada Inteligente 16A Positivo', 'description' => 'Monitoramento de consumo', 'quantity' => 50, 'cost_price' => 95.00, 'sale_price' => 179.90]);
\App\Models\Product::create(['name' => 'Lâmpada Smart RGB 10W Positivo', 'description' => 'Wi-Fi Alexa e Google', 'quantity' => 80, 'cost_price' => 45.00, 'sale_price' => 89.90]);
\App\Models\Product::create(['name' => 'Fechadura Digital Intelbras FR 320', 'description' => 'Senha + cartão + chave', 'quantity' => 8, 'cost_price' => 780.00, 'sale_price' => 1299.00]);